### ISSUE TITLE
Impossible d’exécuter les commandes d'installation

### ISSUE THREAD

**Issue by jbleduigou** [Noethys/Noethysweb#1]
Bonjour,  
J'ai essayé d'installé l'appli.
Malheureusement j'ai cette erreur qui s'affiche dans la console :
```
ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields' (/home/ec2-user/.local/lib/python3.7/site-packages/django/db/models/fields/__init__.
py)
```
J'ai l'impression que cela vient d'une version incompatible de Django.
Ne faudrait-il pas verrouiller la version de chaque dependance dans le fichier `requirements.txt` ?

**Comment by Noethys** [comment]
Bonjour,

Il y avait en effet des erreurs dans le requirements.txt. J'ai fait les modifications nécessaires, vous pouvez de nouveau essayer et tout devrait fonctionner. Notez que j'ai complété le README également.

Bonne journée.
